# Configuration de l'Hôte Virtuel pour WAMP
# À copier dans C:\wamp\bin\apache\apacheX.X.X\conf\extra\httpd-vhosts.conf
# ou à inclure dans votre configuration Apache.

<VirtualHost *:80>
    ServerName localhost
    DocumentRoot "C:/xampp/htdocs"
    <Directory "C:/xampp/htdocs/">
        Options +Indexes +Includes +FollowSymLinks +MultiViews
        AllowOverride All
        Require all granted
    </Directory>
</VirtualHost>

# Accès direct au projet via son propre port (Optionnel)
# Listen 8080
# <VirtualHost *:8080>
#     DocumentRoot "C:/xampp/htdocs/GED-MEF"
#     <Directory "C:/xampp/htdocs/GED-MEF/">
#         Options Indexes FollowSymLinks
#         AllowOverride All
#         Require all granted
#     </Directory>
# </VirtualHost>
