# CONFIGURATION POUR APACHE 2.2 (ANCIEN WAMP)
# A copier dans votre httpd.conf ou extra/httpd-vhosts.conf

<VirtualHost *:80>
    ServerName localhost
    DocumentRoot "C:/wamp/www"
    <Directory "C:/wamp/www/">
        Options Indexes FollowSymLinks MultiViews
        AllowOverride All
        Order Allow,Deny
        Allow from all
    </Directory>
</VirtualHost>

# Si vous gardez le projet dans XAMPP (Déconseillé sur WAMP)
# <Directory "C:/xampp/htdocs/GED-MEF/">
#     Options Indexes FollowSymLinks MultiViews
#     AllowOverride All
#     Order Allow,Deny
#     Allow from all
# </Directory>
